name: Build Cross-Platform Releases

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: Windows
          - os: macos-latest
            platform: macOS
          - os: ubuntu-latest
            platform: Linux

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate venv and install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        venv\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Activate venv and install dependencies (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        venv\Scripts\activate
        python build_releases.py

    - name: Build executable (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        source venv/bin/activate
        python build_releases.py

    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TikTok-Live-Watcher-${{ matrix.platform }}
        path: releases/TikTok-Live-Watcher-${{ matrix.platform }}.zip
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/TikTok-Live-Watcher-Windows/TikTok-Live-Watcher-Windows.zip
          ./artifacts/TikTok-Live-Watcher-macOS/TikTok-Live-Watcher-macOS.zip
          ./artifacts/TikTok-Live-Watcher-Linux/TikTok-Live-Watcher-Linux.zip
        body: |
          ## TikTok Live Watcher Release

          ### Downloads
          - **Windows**: TikTok-Live-Watcher-Windows.zip
          - **macOS**: TikTok-Live-Watcher-macOS.zip
          - **Linux**: TikTok-Live-Watcher-Linux.zip

          ### Installation
          1. Download the zip file for your platform
          2. Extract the zip file
          3. Run the setup script (setup.bat on Windows, setup.sh on macOS/Linux)
          4. Run the TikTok Live Watcher executable

          ### Requirements
          - Setup script handles most dependencies
          - ffmpeg installation may require manual steps (guided by setup script)
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}